site_name: Wiki Makespace Madrid
theme:
  name: readthedocs
  user_color_mode_toggle: true

nav:
  - Inicio: 'index.md'
  - MSM:
      - Introducción:
        - Presentación: 'msm/introduccion/index.md'
        - Makespace Madrid y el Manual de Supervivencia Maker: 'msm/introduccion/sobre-el-manual.md'
